# Generated by Django 4.2.1 on 2023-05-22 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Viúvo', 'Viúvo')], max_length=50, verbose_name='Estado Civil')),
                ('sexo', models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=50, verbose_name='Sexo')),
                ('formacao', models.CharField(blank=True, choices=[('Cursando Técnico', 'Cursando Técnico'), ('Técnico Completo', 'Técnico Completo'), ('Cursando Tecnologia', 'Cursando Tecnologia'), ('Tecnologia Completo', 'Tecnologia Completo'), ('Cursando Licenciatura', 'Cursando Licenciatura'), ('Licenciatura Completo', 'Licenciatura Completo'), ('Cursando Bacharelado', 'Cursando Bacharelado'), ('Bacharelado Completo', 'Bacharelado Completo'), ('Cursando Mestrado', 'Cursando Mestrado'), ('Mestrado Completo', 'Mestrado Completo')], max_length=50, verbose_name='Formação')),
                ('curso', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
